# -----------------------------------------------------------------------------
# auth-service: banco PostgreSQL + chave mestra
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: feature-flags
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpmaWFwMTIzNDVAYXV0aC1zZXJ2aWNlLmNxcHNvcThvcTJhbS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9wb3N0Z3Jlcw==
  MASTER_KEY: MTIzNDU=

---
# -----------------------------------------------------------------------------
# flag-service: banco PostgreSQL dedicado
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: flag-secret
  namespace: feature-flags
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpmaWFwMTIzNDVAZmxhZy1zZXJ2aWNlLmNxcHNvcThvcTJhbS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9wb3N0Z3Jlcw==

---
# -----------------------------------------------------------------------------
# targeting-service: banco PostgreSQL dedicado
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: feature-flags
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpmaWFwMTIzNDVAdGFyZ2V0aW5nLXNlcnZpY2UuY3Fwc29xOG9xMmFtLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Bvc3RncmVz

---
# -----------------------------------------------------------------------------
# evaluation-service: Redis + chave de API de serviço
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: feature-flags
type: Opaque
data:
  REDIS_URL: cmVkaXNzOi8vZXZhbHVhdGlvbi1zZXJ2aWNlLWNhY2hlLThnM3IxeC5zZXJ2ZXJsZXNzLnVzZTEuY2FjaGUuYW1hem9uYXdzLmNvbTo2Mzc5
  SERVICE_API_KEY: MTIzNDU=

---
# -----------------------------------------------------------------------------
# aws-secret: credenciais AWS para analytics-service e evaluation-service
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: feature-flags
type: Opaque
data:
  # Valores reais aplicados diretamente no cluster via:
  # kubectl create secret generic aws-secret -n feature-flags \
  #   --from-literal=AWS_ACCESS_KEY_ID=<SUA_KEY> \
  #   --from-literal=AWS_SECRET_ACCESS_KEY=<SUA_SECRET>
  AWS_ACCESS_KEY_ID: QUNFQU1FWEFNUExFQUNDRVNTS0VZ # base64 de "ACEAMEXAMPLEACCESSKEY"
  AWS_SECRET_ACCESS_KEY: d0pBbEVYQU1QTEVTRUNSRVRBQ0NFU1NLRVkxMjM0NQ== # base64 de "wJALEXAMPLESECRETACCESSKEY12345"
